### PR TITLE
chore: add default .npmrc with pnpm config

### PR DESCRIPTION
**Pull request by joheriks**

### CODE REVIEW

**Review by Artur- — CHANGES_REQUESTED** [review]
This should not be in every v14 project, which uses npm by default

**Comment by joheriks** [comment]
> This should not be in every v14 project, which uses npm by default

Ok, but may need to revisit if there is a decision to support #9834 for v14 pnpm users.

**Comment by Artur-** [comment]
Doesn't Flow add the file by default if you use pnpm?

**Comment by joheriks** [comment]
It does, though first bullet in ticket vaadin/flow#9834  DoD states it should work also before Maven has been run and Flow has had a chance to generate the file:  
> running pnpm i [dependency] works in a Vaadin 19 project downloaded from start.vaadin.com (before and after running mvn first)

**Pull request closed without merging**
