### PR TITLE
Update Spring Boot to 2.7.12

### PR DESCRIPTION
**Pull request by tarekoraby**

### CODE REVIEW

**Comment by czp13** [comment]
The build had compilation error:
```
[13:19:00 ](https://teamcity.vaadin.com/buildConfiguration/Flow_FlowStarters_SkeletonStarterFlowSpring/188963?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=188963_1966_1966&logFilter=debug&logView=flowAware)  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile (default-testCompile) on project spring-skeleton: Compilation failure
[13:19:00 ](https://teamcity.vaadin.com/buildConfiguration/Flow_FlowStarters_SkeletonStarterFlowSpring/188963?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandB
uildChangesSection=true&showLog=188963_1967_1967&logFilter=debug&logView=flowAware)  [ERROR] /opt/agent/work/550f0a2da59af854/src/test/java/org/vaadin/example/MainViewIT.java:[18,46] cannot access org.openqa.selenium.internal.WrapsElement
```

`WrapsElement` (used by testbench) lived in two places `org.openqa.selenium.internal.WrapsElement` and `org.openqa.selenium.WrapsElement`.  

There was a selenium issue fixed to remove the old WrapsElement (which was used by this testbench version)
- https://github.com/SeleniumHQ/selenium/issues/6881

And the new Spring version used the newer selenium which does not have any more in this class in the proper package, and our testbench was fixed later to use the proper package... I was just forced to have the proper dependency for selenium-api to have the  `WrapsElement` in the old package.  

But now anothere test failing and another class is not found (Require).

**Comment by czp13** [comment]
This is the new error :(  Interestingly for the V14 branch this test is not even running as I have checked.
``` 
[19:55:02 ](https://teamcity.vaadin.com/buildConfiguration/Flow_FlowStarters_SkeletonStarterFlowSpring/189313?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true&showLog=189313_2771_2771&logView=flowAware)  java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Require
[19:55:02 ](https://teamcity.vaadin.com/buildConfiguration/Flow_FlowStarters_SkeletonStarterFlowSpring/189313?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true&showLog=189313_2772_2772&logView=flowAware)    at org.openqa.selenium.remote.AbstractDriverOptions.getCapability(AbstractDriverOptions.java:122)
[19:55:02 ](https://teamcity.vaadin.com/buildConfiguration/Flow_FlowStarters_SkeletonStarterFlowSpring/189313?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true&showLog=189313_2773_2773&logView=flowAware)    at org.openqa.selenium.remote.AbstractDriverOptions.lambda$asMap$0(AbstractDriverOptions.java:135)
[19:55:02 ](https://teamcity.vaadin.com/buildConfiguration/Flow_FlowStarters_SkeletonStarterFlowSpring/189313?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true&showLog=189313_2774_2774&logView=flowAware)    at java.util.Collections$SingletonSet.forEach(Collections.java:4767)
```

**Comment by czp13** [comment]
Pinning all the selenium dependencies to the same version (which was for the previous Spring) too bad that I could not find a working and up to date bom for this.

**Comment by czp13** [comment]
And thanks for your collaboration @tarekoraby! 🙇

**Comment by czp13** [comment]
Never ending:
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.openqa.selenium.remote.HttpCommandExecutor
  at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
  at com.vaadin.testbench.parallel.setup.RemoteDriver.createDriver(RemoteDriver.java:41)
  at com.vaadin.testbench.parallel.setup.SetupDriver.setupRemoteDriver(SetupDriver.java:56)
  at com.vaadin.testbench.parallel.setup.SetupDriver.setupRemoteDriver(SetupDriver.java:72)
  at com.vaadin.testbench.parallel.ParallelTest.setup(ParallelTest.java:151)
  ```

**Comment by mcollovati** [comment]
I wonder if it would be easier to pin slenium to the version used by Testbench 6.5 and add a dependency to the old okhttp artifact

```xml
<properties>
    <selenium.version>3.141.59</selenium.version>
</properties>

    <dependencies>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.14.9</version>
        </dependency>
    </dependencies>
```

**Comment by Artur-** [comment]
You need to use the Selenium version TestBench is built with or it probably will not work

**Comment by mcollovati** [comment]
Testbench 6.5.1 uses seleniun 3.141.59

**Review by czp13 — APPROVED** [review]
Thanks for fixing it in the end @mcollovati. Appreciated! 🙇

**Comment by tarekoraby** [comment]
If someone got the chance to test the latest changes, please go ahead and merge.

**Pull request merged**
