### PR TITLE
Produced WAR should be deployable and work in production.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #26.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/39)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/39#-L40rq-Td3td7vCdoj6M:-L40rq-Td3td7vCdoj6N:b-2779gs) (no related file):*
Did you check it in any Tomcat?

I've checked in `8.5.27` and got a startup exception:
```
Caused by: java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.impl.SimpleLoggerFactory loaded from file:/usr/local/Cellar/tomcat/8.5.27/libexec/webapps/ROOT/WEB-INF/lib/slf4j-simple-1.7.25.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.impl.SimpleLoggerFactory
	at org.springframework.util.Assert.instanceCheckFailed(Assert.java:637)
	at org.springframework.util.Assert.isInstanceOf(Assert.java:537)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:271)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:98)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:190)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:67)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:155)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:135)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:87)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 42 more
```

---

*[pom.xml, line 209 at r1](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/39#-L40ppHzvCQtRR2rSk6r:-L40ppHzvCQtRR2rSk6s:b-lzc5yf) ([raw file](https://github.com/vaadin/skeleton-starter-flow-spring/blob/ca1a7226828016e5d675706d385fb84f0083d306/pom.xml#L209)):*
> ```XML
>                         <groupId>com.vaadin</groupId>
>                         <artifactId>flow-maven-plugin</artifactId>
>                         <version>0.0.7</version>
> ```

Should we use `1.0.0.alpha18` as in https://github.com/vaadin/skeleton-starter-flow/blob/master/pom.xml#L141 ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/39)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/39#-L40rq-Td3td7vCdoj6M:-L411Uxc7qN0E0zv87JL:b-tz0l73) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Did you check it in any Tomcat?

I've checked in `8.5.27` and got a startup exception:
```
Caused by: java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.impl.SimpleLoggerFactory loaded from file:/usr/local/Cellar/tomcat/8.5.27/libexec/webapps/ROOT/WEB-INF/lib/slf4j-simple-1.7.25.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.impl.SimpleLoggerFactory
	at org.springframework.util.Assert.instanceCheckFailed(Assert.java:637)
	at org.springframework.util.Assert.isInstanceOf(Assert.java:537)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:271)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:98)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:190)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:67)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:155)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:135)
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:87)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 42 more
```
</blockquote></details>

I've checked https://github.com/vaadin/skeleton-starter-flow in the same Tomcat and it works so I think that the war produced here is not correct.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/39)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/39#-L40rq-Td3td7vCdoj6M:-L4KXryMEaz-TEA746GZ:b-ddxsk9) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I've checked https://github.com/vaadin/skeleton-starter-flow in the same Tomcat and it works so I think that the war produced here is not correct.
</blockquote></details>

Yes, checked also with 8.5.27.
No exceptions. Works as expected.

Your exception means that you have slf4j simple logging binding  which is excluded by the line 
`%regex[WEB-INF/lib/slf4j-simple.*.jar]`.

And the question is how did you get WAR which you are deploying ?
May be it's not a WAR but something before WAR is created (not archived spring-skeleton-1.0-SNAPSHOT contains everything and the things are excluded only in WAR)?

---

*[pom.xml, line 209 at r1](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/39#-L40ppHzvCQtRR2rSk6r:-L4KYjfON2RKWcLW6hiA:b-896fix) ([raw file](https://github.com/vaadin/skeleton-starter-flow-spring/blob/ca1a7226828016e5d675706d385fb84f0083d306/pom.xml#L209)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Should we use `1.0.0.alpha18` as in https://github.com/vaadin/skeleton-starter-flow/blob/master/pom.xml#L141 ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/39)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/39#-L40rq-Td3td7vCdoj6M:-L4KgCVX2k-MoVPkUH2-:b-bjxtdc) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Yes, checked also with 8.5.27.
No exceptions. Works as expected.

Your exception means that you have slf4j simple logging binding  which is excluded by the line 
`%regex[WEB-INF/lib/slf4j-simple.*.jar]`.

And the question is how did you get WAR which you are deploying ?
May be it's not a WAR but something before WAR is created (not archived spring-skeleton-1.0-SNAPSHOT contains everything and the things are excluded only in WAR)?
</blockquote></details>

All right, that's my Tomcat adding it, now I get it, sorry.

---

*[pom.xml, line 209 at r1](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/39#-L40ppHzvCQtRR2rSk6r:-L4KgYjq1oc8Tq2PUCyq:b-8nlap4) ([raw file](https://github.com/vaadin/skeleton-starter-flow-spring/blob/ca1a7226828016e5d675706d385fb84f0083d306/pom.xml#L209)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/39)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/39)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pom.xml, line 209 at r1](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/39#-L40ppHzvCQtRR2rSk6r:-L4LEdLICUmomnICkQ10:bnbwenk) ([raw file](https://github.com/vaadin/skeleton-starter-flow-spring/blob/ca1a7226828016e5d675706d385fb84f0083d306/pom.xml#L209)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Not yet.
</blockquote></details>

Ops.
Now it's done.
Have no idea why I don't get updates from via email for this repo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/39)*

**Pull request merged**
