### PR TITLE
Use Java 15 by default

### PR DESCRIPTION
**Pull request by Artur-**
Removed encoding properties already set in parent pom

### CODE REVIEW

**Comment by samie** [comment]
I'm not sure where/how this is used, but project compilation with openjdk 11.0.5 2019-10-15 LTS gives you:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project spring-skeleton: Fatal error compiling: error: invalid target release: 15`

**Comment by Artur-** [comment]
Indeed. You need JDK 15 for a Java 15 project

**Comment by samie** [comment]
I mean, is 15 now requirement for new Vaadin projects or this change about something else?

**Comment by Artur-** [comment]
This change would make Java 15 used/required by default. As long as the code does not use any Java 15 features, you could go back to even Java 8 by changing pom.xml

**Comment by mstahv** [comment]
I think the title suggestion makes no sense. Vast majority of users are in 8 or 11 and it is just as easy for those who want to use latest language features to update the version in their project. The java version should be lowest possible, based on the language features we use in the example.

pom cleanup makes sense otherwise, split the other changes to https://github.com/vaadin/skeleton-starter-flow-spring/pull/452

**Comment by Artur-** [comment]
This has been implemented in start.vaadin.com instead

**Pull request closed without merging**
