### PR TITLE
Update platform dependency to beta11

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/70)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[pom.xml, line 79 at r1](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/70#-LD5ZF6RCd06Q4xoZ8Y9:-LD5ZF6SDPQxUj3lHE1o:b-uyqm7s) ([raw file](https://github.com/vaadin/skeleton-starter-flow-spring/blob/baf28af6f17f3ef292659ddafbbe7269aae234fe/pom.xml#L79)):*
> ```
> <version>${vaadin.version}</version>
> ```

Boot starter has its own version or is it agreed that it's the same as vaadin platform ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/70)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[pom.xml, line 79 at r1](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/70#-LD5ZF6RCd06Q4xoZ8Y9:-LD5ZnPb8LJgip0qpOYD:bz7it7n) ([raw file](https://github.com/vaadin/skeleton-starter-flow-spring/blob/baf28af6f17f3ef292659ddafbbe7269aae234fe/pom.xml#L79)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> <version>${vaadin.version}</version>
> ```

Boot starter has its own version or is it agreed that it's the same as vaadin platform ?
</blockquote></details>

```
After everything is done, release a new version of vaadin-spring-boot-starter that follows the platform version (yes, there is a version skip from beta3 to beta 9 or 10)
```

as it has been stated in the issue ticket. the spring-boot-starter will follow the platform version, from now on

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/70)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[pom.xml, line 79 at r1](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/70#-LD5ZF6RCd06Q4xoZ8Y9:-LD5_8uKEeoA5Saner1R:brujztc) ([raw file](https://github.com/vaadin/skeleton-starter-flow-spring/blob/baf28af6f17f3ef292659ddafbbe7269aae234fe/pom.xml#L79)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

```
After everything is done, release a new version of vaadin-spring-boot-starter that follows the platform version (yes, there is a version skip from beta3 to beta 9 or 10)
```

as it has been stated in the issue ticket. the spring-boot-starter will follow the platform version, from now on
</blockquote></details>

OK, thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/70#-:-LD5_BAjDV89gO9oHrs3:bnfp4nl)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/70#-:-LD5_QrUDvh7Ry6K7LNV:bnfp4nl)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/70#-:-LDenEWa1cHHcLYN-9pS:bnfp4nl)*

**Pull request merged**
