### PR TITLE
fix: Update package.json and pnpm-lock with fusion deps

### PR DESCRIPTION
**Pull request by mshabarov**
## Description

Adds fusion dependencies introduced by this change in flow https://github.com/vaadin/flow/pull/11420.

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Review by ZheSun88 — APPROVED** [review]

**Comment by Artur-** [comment]
Why was this done? Running `mvn` in the project removes the dependencies

**Comment by mshabarov** [comment]
@Artur- If not adding these dependencies, starter's IT tests fail with the latest flow `8.0` snapshot/release with:

```
[14:54:35][Step 3/5] ?ERROR? Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date with package.json
```

**Comment by Artur-** [comment]
How is that related to including MobX?

**Comment by Artur-** [comment]
The next version update will remove the dependencies as they should not be there. Sounds like you are fixing something in the wrong way

**Comment by mshabarov** [comment]
As I understand the problem, this 'frozen-lockfile' error happens when the pnpm lock differs from package json.
Seems that this error is thrown before the packages are updated with fusion mob-x dependecies.
As the package json and pnpm lock are stored in version control system, I thought that I need to commit these dependecies change.

Moreover, here is a commit in v22 which does pretty the same https://github.com/vaadin/skeleton-starter-flow-spring/commit/19fb0e83c5fa8f84386b3bf8fe5cc4d7417418e9

**Comment by Artur-** [comment]
I see, I was running with beta2 for some reason and that removes the packages. With rc1 it doesn't

**Comment by mshabarov** [comment]
Yes, I forgot to mention that it was for flow `8.0.0.rc1`.

**Pull request merged**
