### PR TITLE
Update platform version and exclude flow-server dependency from it

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/15)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/15#-KzhO1-qxM32Oos8VMB7:-KzhO1-qxM32Oos8VMB8:b8to0ag) (no related file):*
Why would anyone using this project ever want to have any overrides for Flow versions (i.e. `flow.project.version`) instead of always only using a platform version (i.e. `vaadin.project.version`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/15)*

**Comment by caalador** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/15#-KzhO1-qxM32Oos8VMB7:-KzhgIJR5lplyNn1M2ij:b-x80vkr) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Why would anyone using this project ever want to have any overrides for Flow versions (i.e. `flow.project.version`) instead of always only using a platform version (i.e. `vaadin.project.version`).
</blockquote></details>

I would expect to not have the need to know the flow version just use what ever vaadin10 provides as that's certain to work. Now there is a missmatch in version between flow-server, flow-data, flow-client etc packages.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/15)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/15#-KzhO1-qxM32Oos8VMB7:-Kzi2adFFkMrUrih4ktg:b-ovw4sl) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I would expect to not have the need to know the flow version just use what ever vaadin10 provides as that's certain to work. Now there is a missmatch in version between flow-server, flow-data, flow-client etc packages.
</blockquote></details>

One impact of only using the platform version and no Flow version numbers is that the Starter would have to be updated after platform releases instead of after Flow releases. The benefit is that it would be so much clearer for the user.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/15)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/15#-KzhO1-qxM32Oos8VMB7:-KzxD62v7bpjdXG7fZQU:b-b7leb6) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

One impact of only using the platform version and no Flow version numbers is that the Starter would have to be updated after platform releases instead of after Flow releases. The benefit is that it would be so much clearer for the user.
</blockquote></details>

The project depends on Spring add-on and platform.
Spring add-on depends on the specific Flow version which may mismatch the the platform version.

So either Spring add-on should depend on platform version instead of Flow directly or there is always a chance to have version mismatch (and here is the way of avoiding this mismatch).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/15)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/15#-KzhO1-qxM32Oos8VMB7:-Kzxi7wYw2x0yV4-DUUQ:b-1xtndr) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The project depends on Spring add-on and platform.
Spring add-on depends on the specific Flow version which may mismatch the the platform version.

So either Spring add-on should depend on platform version instead of Flow directly or there is always a chance to have version mismatch (and here is the way of avoiding this mismatch).
</blockquote></details>

The platform BOM defines a version number for the Spring add-on that is in sync with the rest of the Flow dependencies for that platform version. This starter can thus depend on the add-on without defining any version number for it. See https://github.com/vaadin/trippy/blob/master/trippy-ui/pom.xml for an example of this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/15)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/15#-KzhO1-qxM32Oos8VMB7:-L-5Vc2R_zwBFmB7ODAT:boyexbg) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

The platform BOM defines a version number for the Spring add-on that is in sync with the rest of the Flow dependencies for that platform version. This starter can thus depend on the add-on without defining any version number for it. See https://github.com/vaadin/trippy/blob/master/trippy-ui/pom.xml for an example of this.
</blockquote></details>

Done. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/15)*

**Comment by ZheSun88** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/15)*

**Pull request merged**
