### PR TITLE
Use Java 11 for V19

### PR DESCRIPTION
**Pull request by Artur-**
Java 11 is the latest LTS

### CODE REVIEW

**Comment by Artur-** [comment]
@ZheSun88 can you fix the validation build for this?

**Comment by ZheSun88** [comment]
@Artur- As TC doesn't know the target branch of a PR, it is difficult to change the java_home for just one branch without touching another. Unless we create a separate validation to just run this branch.  

another question: I think we do validation to verify that the starter is working with the java version we have mentioned in platform release note. So does it mean that Java 11 becomes the minimal support since Vaadin 19?

**Comment by Artur-** [comment]
We are not dropping Java 8 support. The point of the starter is not to validate that Vaadin is compatible with Java 8. The point is to provide a good starting point for new projects. For that, Java 11 is more suitable today than Java 8.

Anyway, let's merge #465 / #466 first and see if we make the Java version an option in start.vaadin.com or if we want to change it here. cc @samie

**Comment by Artur-** [comment]
This has been implemented in start.vaadin.com instead

**Pull request closed without merging**
