### PR TITLE
Configure test logger instead of redirecting all output

### LINKED ISSUE #87: Test output not visible
You've added:

    
    <maven.test.redirectTestOutputToFile>true</maven.test.redirectTestOutputToFile>

This maybe a nice idea but redirects ALL test output to a file which is very inconvenient when building the application in a CI server like GitHub Actions.

Please remove this configuration.

If you just want to suppress the selenium output you should check how to configure logging! Btw it's not Selenium but netty and the driver manger.

### PR DESCRIPTION
**Pull request by Artur-**
Fixes https://github.com/vaadin/starters/issues/87

### CODE REVIEW

**Comment by tarekoraby** [comment]
It would be nice to add some comments to the new file explaining what it is and what it's doing.

**Comment by Artur-** [comment]
It would also be nice to understand why this is needed at all :)

**Comment by Artur-** [comment]
@manolo ?

**Review by manolo — APPROVED** [review]

**Comment by ZheSun88** [comment]
> would also be nice to understand why this is needed at all :)

i remember the output gets quite verbose after selenium version update to 4.5.0 (maybe wrong)

**Comment by manolo** [comment]
@tarekoraby I guess the file content does not need so much explanation, java devs normally are familiar with logging configuration. This is just removing from the console output noisy lines, in case of errors or important info they are still displayed.

**Comment by tarekoraby** [comment]
I'm not familiar with `logback-test.xml`, and I suspect some sizable percentage of the framework userbase will also find this unfamiliar, and they could benefit from some explanation.

**Comment by Artur-** [comment]
With the given log conf I still see a lot of debug output from `org.apache.hc.client5.http.wire` after removing `/Users/artur/.cache/selenium/ ` so that webdrivermanager downloads the driver

**Comment by Artur-** [comment]
Also it shows license checker debug output

**Comment by Artur-** [comment]
Simplified to what https://docs.spring.io/spring-boot/docs/2.6.1/reference/htmlsingle/#howto.logging.logback calls "A typical custom logback.xml file"

**Pull request merged**
