### PR TITLE
Make app /META-INF/resources as static web resource in Jar exec case

### PR DESCRIPTION
**Pull request by denis-anisimov**
Part of vaadin/flow#8705

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/381)

### CODE REVIEW

**Comment by Artur-** [comment]
This does not at all look like something I would want or should need to have in my project. Is this a Spring Boot bug you are working around or something else?

**Comment by denis-anisimov** [comment]
I think it's impossible to make a bug against Spring boot regarding this issue...
There are a number of similar reports against Spring which it seems treated as not a bug.....

**Comment by denis-anisimov** [comment]
But yes, technically this is a Spring boot issue.

**Comment by Artur-** [comment]
As far as I know, this is not needed

**Pull request closed without merging**
