### PR TITLE
Update to alpha11

### PR DESCRIPTION
**Pull request by ZheSun88**
Update to Flow alpha11 and vaadin alpha8

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/18)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 8 at r3](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/18#-L-60neoFzLRSdUASPLN:-L-60neoFzLRSdUASPLO:bin176u) ([raw file](https://github.com/vaadin/skeleton-starter-flow-spring/blob/1b9b2cee8454ddc4f06de8d86d30ed60b9a127a3/pom.xml#L8)):*
> ```XML
>     <artifactId>spring-skeleton</artifactId>
>     <name>Spring Flow Application Skeleton</name>
>     <version>1.0.0.alpha10</version>
> ```

How do we update this version? Should it be the same as `flow.project.version`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/18)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pom.xml, line 8 at r3](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/18#-L-60neoFzLRSdUASPLN:-L-623pknvXXjmVgfhyc:b-f2j6bk) ([raw file](https://github.com/vaadin/skeleton-starter-flow-spring/blob/1b9b2cee8454ddc4f06de8d86d30ed60b9a127a3/pom.xml#L8)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

How do we update this version? Should it be the same as `flow.project.version`?
</blockquote></details>

That is a great question!!. just confirmed with Pekka... that may not be that trivial... waiting for a call them

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/18)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/18)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow-spring/18#-:-L-6U2PSOQ5auKUyQJsY:bnfp4nl)*

**Pull request merged**
